### ISSUE TITLE
Attempting to run the program results in a missing module message

### ISSUE THREAD

**Issue by willkill07** [mucsci-students/2021sp-420-MontyPython#193]
```
Traceback (most recent call last):
  File "/Users/wkillian/Desktop/2021sp-420-MontyPython/Monty.py", line 18, in <module>
    GUI.main(False)
  File "/Users/wkillian/Desktop/2021sp-420-MontyPython/GUI.py", line 3, in main
    import GUIController
  File "/Users/wkillian/Desktop/2021sp-420-MontyPython/GUIController.py", line 8, in <module>
    from PIL import Image
ModuleNotFoundError: No module named 'PIL'
```

I believe pillow needs to be listed in requirements.txt?

**Comment by willkill07** [comment]
After adding `pillow`, I get another error:

```
Traceback (most recent call last):
  File "/Users/wkillian/Desktop/2021sp-420-MontyPython/Monty.py", line 18, in <module>
    GUI.main(False)
  File "/Users/wkillian/Desktop/2021sp-420-MontyPython/GUI.py", line 6, in main
    from GUIMainWindow import MainWindow
  File "/Users/wkillian/Desktop/2021sp-420-MontyPython/GUIMainWindow.py", line 5, in <module>
    import numpy as np
ModuleNotFoundError: No module named 'numpy'
```

**Comment by willkill07** [comment]
After adding `numpy`, I get another error:

```
Traceback (most recent call last):
  File "/Users/wkillian/Desktop/2021sp-420-MontyPython/Monty.py", line 18, in <module>
    GUI.main(False)
  File "/Users/wkillian/Desktop/2021sp-420-MontyPython/GUI.py", line 6, in main
    from GUIMainWindow import MainWindow
  File "/Users/wkillian/Desktop/2021sp-420-MontyPython/GUIMainWindow.py", line 7, in <module>
    from pathfinding.core.diagonal_movement import DiagonalMovement
ModuleNotFoundError: No module named 'pathfinding'
```
